### ISSUE TITLE
1.2.2.2 Documentación requerimientos

### ISSUE THREAD

**Issue by dangarsoftpoli** [ISWPOLI/TANGRAM-TEAM#11]
*descripcion*
realizacion de la documentacion segun estandares de la informacion correpondiente a los requerimientos del sistemas

rol analista
esfuerzo 6 horas
prioridad alta

**Comment by MichaelBordaPoli** [comment]
#11
Se adjuntan los requerimientos elaborados en el formato recomendado en el moodle.
[REQUERIMIENTOS EN WORD.docx](https://github.com/ISWPOLI/TANGRAM-TEAM/files/1450392/REQUERIMIENTOS.EN.WORD.docx)
