### ISSUE TITLE
1. Elicitación y Diseño

### ISSUE THREAD

**Issue by libohorquez** [ISWPOLI/TANGRAM-TEAM#13]
Contiene todos los procesos relacionados con levantamiento de información y diseño.
Describe los principales conceptos como las entrevistas, encuestas y diseño.

**Comment by libohorquez** [comment]
Describe los principales conceptos como las entrevistas, encuestas y diseño.

**Comment by MichaelBordaPoli** [comment]
Se realizo proceso de elicitación.
