### ISSUE TITLE
1.2.4.1 Especificación gráfica casos de uso

### ISSUE THREAD

**Issue by elbetancourt1** [ISWPOLI/TANGRAM-TEAM#14]
**Descripción**
 
Actividad que abarca el establecimiento de los roles y casos de uso disoponibles para el sistema de acuerdo con sus requerimientos. se debe establecer de forma grafica de manera que cumpla con los diagramas UML para tal fin 

duracion 6 horas

**Comment by libohorquez** [comment]
![caso de uso administrador](https://user-images.githubusercontent.com/30841573/30007642-6f000d58-90d9-11e7-9ed6-9f243728ee0c.png)
![caso de uso despachador](https://user-images.githubusercontent.com/30841573/30007643-6f029c30-90d9-11e7-84de-d268c7104038.png)
![caso de uso domiciliario](https://user-images.githubusercontent.com/30841573/30007645-6f202e30-90d9-11e7-97d2-a3822133a54e.png)
![caso de uso supervisor administrativo](https://user-images.githubusercontent.com/30841573/30007644-6f1e9c5a-90d9-11e7-9a8a-3517bcf38e0b.png)
