### ISSUE TITLE
1.1 Levantamiento de informacion

### ISSUE THREAD

**Issue by elbetancourt1** [ISWPOLI/TANGRAM-TEAM#15]
**Descripción** 
Proceso por medio del cual se realizan, entrevistas, encuestas y análisis, relacionados al funcionamiento del aplicativo.

**Comment by MichaelBordaPoli** [comment]
Se realizo el proceso de  entrevistas, encuestas y análisis, relacionados al funcionamiento del aplicativo. Se realizaron commits en las issues asociadas.
