### ISSUE TITLE
1.1.3 Investigación

### ISSUE THREAD

**Issue by elbetancourt1** [ISWPOLI/TANGRAM-TEAM#18]
**Descripción**

Realizar un trabajo investigativo, que identifique los principales problemas que entra a resolver la aplicación, adicional mente crear un modelo de negocio para tener una idea más clara de todo el proceso.

**Comment by MichaelBordaPoli** [comment]
Se realiza entrega de la definición de problemas
[definicion del problema.docx](https://github.com/ISWPOLI/TANGRAM-TEAM/files/1494590/definicion.del.problema.docx)
