### ISSUE TITLE
1.2.1.2 Documento selección metodología

### ISSUE THREAD

**Issue by libohorquez** [ISWPOLI/TANGRAM-TEAM#60]
**descripción**

Elaboración documento de qué metodología se usará en el desarrollo del proyecto.

**Comment by MichaelBordaPoli** [comment]
Se adjunta documento de metodologia seleccionada
[Metodología Implementada.docx](https://github.com/ISWPOLI/TANGRAM-TEAM/files/1494612/Metodologia.Implementada.docx)
