### ISSUE TITLE
1.2.1.3 Documento de las herramientas y Framework

### ISSUE THREAD

**Issue by libohorquez** [ISWPOLI/TANGRAM-TEAM#61]
**descripción**

Elaboración de documento descriptivo de las herramientas y framework a usar en el desarrollo del proyecto.

**Comment by MichaelBordaPoli** [comment]
Se adjunta documento de frameworks y herramientas usadas.

**Comment by MichaelBordaPoli** [comment]
[Herramientas y frameworks usados en D-Control.docx](https://github.com/ISWPOLI/TANGRAM-TEAM/files/1494603/Herramientas.y.frameworks.usados.en.D-Control.docx)
