### ISSUE TITLE
3.1 Pruebas

### ISSUE THREAD

**Issue by libohorquez** [ISWPOLI/TANGRAM-TEAM#73]
Actividades relacionadas con la realización de pruebas del aplicativo.

**Comment by MichaelBordaPoli** [comment]
Se adjuntan evidencias de pruebas y script de pruebas con los resultados.
[ScriptPruebas.xlsx](https://github.com/ISWPOLI/TANGRAM-TEAM/files/1494568/ScriptPruebas.xlsx)
