### ISSUE TITLE
3.1.1 Plan de pruebas

### ISSUE THREAD

**Issue by libohorquez** [ISWPOLI/TANGRAM-TEAM#74]
**descripción**

Elaboración del plan de pruebas del aplicativo

**Comment by MichaelBordaPoli** [comment]
[Plan_DePruebas_D-Control.docx](https://github.com/ISWPOLI/TANGRAM-TEAM/files/1486218/Plan_DePruebas_D-Control.docx)

**Comment by MichaelBordaPoli** [comment]
Se adjunta plan de pruebas de la aplicaciòn
